development:
  adapter: mysql
  encoding: utf8
  database: bc_elr_db
  pool: 5
  username: bc-dev-admin
  password: bcdevpw
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000


